on:
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
