on:
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: 'rust:latest'
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
